name: Build & Deploy .NET App to Hetzner VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH to Hetzner VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HETZNER_SERVER_IP }}
          username: ${{ secrets.HETZNER_SSH_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd ~/myapp
            git pull origin main
            docker-compose up -d --build
            docker image prune -af || true
